# Generated by Django 5.2.7 on 2025-10-14 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="ate_added",
            new_name="date_added",
        ),
    ]
