# Generated by Django 5.2.7 on 2025-10-14 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0003_rename_ate_added_topic_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
